#!/usr/bin/env bash
# Idempotent setup for a new (personal) machine.
#   git clone git@github.com:jellison/dotfiles.git ~/code/dotfiles
#   cd ~/code/dotfiles && ./bootstrap.sh
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STOW_DIR="$(dirname "$DOTFILES")"
PKG="$(basename "$DOTFILES")"

echo "==> 1/5 Homebrew"
if ! command -v brew >/dev/null 2>&1; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
# make brew available in this shell (Apple Silicon / Intel)
eval "$([ -x /opt/homebrew/bin/brew ] && /opt/homebrew/bin/brew shellenv || /usr/local/bin/brew shellenv)"

echo "==> 2/5 Packages (brew bundle)"
brew bundle --file="$DOTFILES/Brewfile"

echo "==> 3/5 Link dotfiles into \$HOME (GNU stow)"
# Herdr keeps its runtime state next to its config -- sockets, logs, session
# snapshots -- so ~/.config/herdr has to be a real directory. Left absent, stow
# would fold it into a single symlink pointing at this repo and Herdr would
# write all of that into version control. Creating it first leaves stow no
# choice but to link config.toml on its own.
mkdir -p "$HOME/.config/herdr"
if stow --dir="$STOW_DIR" --target="$HOME" --restow "$PKG"; then
  echo "    linked."
else
  echo "    stow reported conflicts (a real file already exists where a symlink"
  echo "    should go). Resolve, then re-run, e.g.:"
  echo "      stow --dir=\"$STOW_DIR\" --target=\"\$HOME\" --adopt \"$PKG\"   # pulls existing file into repo"
  echo "      # or back up/remove the conflicting file, then re-run this script"
fi

echo "==> 4/5 Fonts"
mkdir -p "$HOME/Library/Fonts"
cp -n "$DOTFILES"/fonts/*.OTF "$HOME/Library/Fonts/" 2>/dev/null || true

echo "==> 5/5 Claude Code config (common + optional local overlay)"
# Two files in ~/.claude are GENERATED here (never stowed, never committed):
#   CLAUDE.md      — a real import stub (a symlinked ~/.claude/CLAUDE.md is skipped
#                    in some sessions, so it must be a real file)
#   settings.json  — a jq deep-merge of the common fragment and, if this machine
#                    has a local overlay, the overlay's fragment
# The curated skills/commands/hooks/claudeui.json/writing-guide.md were already
# linked into ~/.claude by stow in step 3/5.
#
# Machine-local overlay pointer (untracked; see .gitignore): if present it sets
# CLAUDE_LOCAL_DIR and stows the private overlay repo into $HOME. Sourced before we
# render/merge so the overlay's inputs are visible.
if [[ -f "$DOTFILES/bootstrap.local.sh" ]]; then
  # shellcheck source=/dev/null
  source "$DOTFILES/bootstrap.local.sh"
fi

claude_dir="$HOME/.claude"
mkdir -p "$claude_dir"

# 5a. Render the CLAUDE.md import stub (paths are expanded to absolutes now).
{
  echo "<!-- Generated by dotfiles bootstrap.sh — do not edit. Edit the sources: -->"
  echo "<!--   common: $DOTFILES/claude-sources/CLAUDE.common.md -->"
  if [[ -n "${CLAUDE_LOCAL_DIR:-}" ]]; then
    echo "<!--   local:  $CLAUDE_LOCAL_DIR/claude-sources/CLAUDE.local.md -->"
  fi
  echo "@$DOTFILES/claude-sources/CLAUDE.common.md"
  if [[ -n "${CLAUDE_LOCAL_DIR:-}" && -f "$CLAUDE_LOCAL_DIR/claude-sources/CLAUDE.local.md" ]]; then
    echo "@$CLAUDE_LOCAL_DIR/claude-sources/CLAUDE.local.md"
  fi
} > "$claude_dir/CLAUDE.md"
echo "    rendered ~/.claude/CLAUDE.md"

# 5b. Assemble ~/.claude/settings.json = deepmerge(common, local?). Object keys
#     merge recursively; permission lists are unioned (deduped).
common_settings="$DOTFILES/claude-sources/settings.common.json"
local_settings=""
if [[ -n "${CLAUDE_LOCAL_DIR:-}" && -f "$CLAUDE_LOCAL_DIR/claude-sources/settings.local.json" ]]; then
  local_settings="$CLAUDE_LOCAL_DIR/claude-sources/settings.local.json"
fi

if [[ -n "$local_settings" ]]; then
  jq -s '
    .[0] as $c | .[1] as $l |
    ($c * $l)
    | .permissions.allow = (($c.permissions.allow // []) + ($l.permissions.allow // []) | unique)
    | .permissions.deny  = (($c.permissions.deny  // []) + ($l.permissions.deny  // []) | unique)
    | .permissions.ask   = (($c.permissions.ask   // []) + ($l.permissions.ask   // []) | unique)
  ' "$common_settings" "$local_settings" > "$claude_dir/settings.json"
  echo "    merged ~/.claude/settings.json (common + local overlay)"
else
  jq '.' "$common_settings" > "$claude_dir/settings.json"
  echo "    wrote ~/.claude/settings.json (common only)"
fi

# Language-manager globals (npm/cargo). Guarded: only run if the toolchain is
# present. On a fresh machine install node (via nvm) / rust first, then re-run.
if command -v npm >/dev/null 2>&1; then
  echo "==> npm globals"
  npm install -g @earendil-works/pi-coding-agent yarn elm-land lamdera
else
  echo "==> skipping npm globals (no npm yet; install node via nvm, then re-run)"
fi
# mermaid-cli (brew) ships puppeteer but not a browser. Install the exact
# chrome-headless-shell its bundled puppeteer pins into ~/.cache/puppeteer,
# using that same puppeteer so versions always match. Idempotent.
if command -v mmdc >/dev/null 2>&1; then
  echo "==> mermaid-cli headless Chrome"
  MMDC_NM="$(brew --prefix mermaid-cli)/libexec/lib/node_modules/@mermaid-js/mermaid-cli/node_modules"
  node "$MMDC_NM/puppeteer/lib/puppeteer/node/cli.js" browsers install chrome-headless-shell
fi
if command -v cargo >/dev/null 2>&1; then
  echo "==> cargo tools"
  cargo install cargo-bundle
fi

cat <<'EOF'

Done. Manual follow-ups (not handled by this script):
  * Go toolchain — install via your Go version manager (company/personal method),
    then `go install` gopls/gofumpt/goimports/delve as needed.
  * On first `nvim` launch, plugins install pinned to lua/lazy-lock.json.
  * BerkeleyMono is licensed to you; its font files are vendored in fonts/.
EOF
