gui:
  showCommandLog: false
  scrollHeight: 10
git:
  paging:
    externalDiffCommand: "difft --color=always --display side-by-side-show-both"
  log:
    order: date-order
    showWholeGraph: true
customCommands:
  - key: "<c-o>"
    context: "worktrees"
    description: "Copy worktree path"
    command: "printf %s {{.SelectedWorktree.Path | quote}} | pbcopy"
    output: none
