-- Markdown hard-wrap while typing. The Tree-sitter-aware setup temporarily
-- disables wrapping inside structured blocks such as tables, lists, quotes,
-- headings, HTML, and code. The same module handles save/manual formatting.
--
-- This does not sweep the buffer; only the top-level prose being edited wraps.
--
-- Reflow existing prose on demand:
--   gqap   reflow the current paragraph
--   gqip   reflow paragraph (inner)
--   gggqG  reflow the whole file
--   gq{motion} / (visual) gq   reflow a range
require("config.markdown_reflow").setup_live_wrap(0, 80)
