add_newline = false

# [character]
# success_symbol = "[➜](bold green)"

[directory]
truncate_to_repo = false

[docker_context]
disabled = true

[git_status]
disabled = true

[package]
disabled = true
